package inf.san.mcm.db.update.model.queries;

public class DbCardsQueries {

	public static final String SELECT = """
			SELECT artist, 
				artistIds, 
				asciiName, 
				attractionLights, 
				availability, 
				boosterTypes, 
				borderColor, 
				cardParts, 
				colorIdentity, 
				colorIndicator, 
				colors, 
				defense, 
				duelDeck, 
				edhrecRank, 
				edhrecSaltiness, 
				faceConvertedManaCost, 
				faceFlavorName, 
				faceManaValue, 
				faceName, 
				finishes, 
				flavorName, 
				flavorText, 
				frameEffects, 
				frameVersion, 
				hand, 
				hasAlternativeDeckLimit, 
				hasContentWarning, 
				hasFoil, 
				hasNonFoil, 
				isAlternative, 
				isFullArt, 
				isFunny, 
				isOnlineOnly, 
				isOversized, 
				isPromo, 
				isRebalanced, 
				isReprint, 
				isReserved, 
				isStarter, 
				isStorySpotlight, 
				isTextless, 
				isTimeshifted, 
				keywords, 
				"language", 
				layout, 
				leadershipSkills, 
				life, 
				loyalty, 
				manaCost, 
				manaValue, 
				name, 
				"number", 
				originalPrintings, 
				originalReleaseDate, 
				originalText, 
				originalType, 
				otherFaceIds, 
				power, 
				printings, 
				promoTypes, 
				rarity, 
				rebalancedPrintings, 
				relatedCards, 
				securityStamp, 
				setCode, 
				side, 
				signature, 
				sourceProducts, 
				subsets, 
				subtypes, 
				supertypes, 
				"text", 
				toughness, 
				"type", 
				types, 
				uuid, 
				variations, 
				watermark
			FROM cards
			""";
	public static final String EXISTS_BY_UUID = """
			select 
			    case 
			        when exists (
					    select 1 from cards where uuid = ?
					) then true
					else false
				end
			as exist
			""";
	public static final String UPDATE = """
			UPDATE cards
			SET artist = ?, 
				artistIds = ?, 
				asciiName = ?, 
				attractionLights = ?, 
				availability = ?, 
				boosterTypes = ?, 
				borderColor = ?, 
				cardParts = ?, 
				colorIdentity = ?, 
				colorIndicator = ?, 
				colors = ?, 
				defense = ?, 
				duelDeck = ?, 
				edhrecRank = ?, 
				edhrecSaltiness = ?, 
				faceConvertedManaCost = ?, 
				faceFlavorName = ?, 
				faceManaValue = ?, 
				faceName = ?, 
				finishes = ?, 
				flavorName = ?, 
				flavorText = ?, 
				frameEffects = ?, 
				frameVersion = ?, 
				hand = ?, 
				hasAlternativeDeckLimit = ?, 
				hasContentWarning = ?, 
				hasFoil = ?, 
				hasNonFoil = ?, 
				isAlternative = ?, 
				isFullArt = ?, 
				isFunny = ?, 
				isOnlineOnly = ?, 
				isOversized = ?, 
				isPromo = ?, 
				isRebalanced = ?, 
				isReprint = ?, 
				isReserved = ?, 
				isStarter = ?, 
				isStorySpotlight = ?, 
				isTextless = ?, 
				isTimeshifted = ?, 
				keywords = ?, 
				"language" = ?, 
				layout = ?, 
				leadershipSkills = ?, 
				life = ?, 
				loyalty = ?, 
				manaCost = ?, 
				manaValue = ?, 
				name = ?, 
				"number" = ?, 
				originalPrintings = ?, 
				originalReleaseDate = ?, 
				originalText = ?, 
				originalType = ?, 
				otherFaceIds = ?, 
				power = ?, 
				printings = ?, 
				promoTypes = ?, 
				rarity = ?, 
				rebalancedPrintings = ?, 
				relatedCards = ?, 
				securityStamp = ?, 
				setCode = ?, 
				side = ?, 
				signature = ?, 
				sourceProducts = ?, 
				subsets = ?, 
				subtypes = ?, 
				supertypes = ?, 
				"text" = ?, 
				toughness = ?, 
				"type" = ?, 
				types = ?, 
				variations = ?, 
				watermark = ?
			WHERE uuid = ?
			""";
	public static final String INSERT = """
			INSERT INTO cards (
				artist, 
				artistIds, 
				asciiName, 
				attractionLights, 
				availability, 
				boosterTypes, 
				borderColor, 
				cardParts, 
				colorIdentity, 
				colorIndicator, 
				colors, 
				defense, 
				duelDeck, 
				edhrecRank, 
				edhrecSaltiness, 
				faceConvertedManaCost, 
				faceFlavorName, 
				faceManaValue, 
				faceName, 
				finishes, 
				flavorName, 
				flavorText, 
				frameEffects, 
				frameVersion, 
				hand, 
				hasAlternativeDeckLimit, 
				hasContentWarning, 
				hasFoil, 
				hasNonFoil, 
				isAlternative, 
				isFullArt, 
				isFunny, 
				isOnlineOnly, 
				isOversized, 
				isPromo, 
				isRebalanced, 
				isReprint, 
				isReserved, 
				isStarter, 
				isStorySpotlight, 
				isTextless, 
				isTimeshifted, 
				keywords, 
				"language", 
				layout, 
				leadershipSkills, 
				life, 
				loyalty, 
				manaCost, 
				manaValue, 
				name, 
				"number", 
				originalPrintings, 
				originalReleaseDate, 
				originalText, 
				originalType, 
				otherFaceIds, 
				power, 
				printings, 
				promoTypes, 
				rarity, 
				rebalancedPrintings, 
				relatedCards, 
				securityStamp, 
				setCode, 
				side, 
				signature, 
				sourceProducts, 
				subsets, 
				subtypes, 
				supertypes, 
				"text", 
				toughness, 
				"type", 
				types, 
				uuid, 
				variations, 
				watermark
			) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
				?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
				?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
				?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
			""";

}
